name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run Prettier lint
        run: npm run lint
      - name: Run tests (dummy)
        run: echo "Running tests (dummy)"
      - name: Build project (dummy)
        run: echo "Building project (dummy)" 